### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by vespino** [rehy/cordova-plugin-sms-receiver#1]
I'm getting a syntax error on this line of code:

```
SmsReceiver.startReception(({messageBody, originatingAddress}) => {
```

Also using it with Phonegap Build, build fails. I have attached the log file. [build.txt](https://github.com/rehy/cordova-plugin-sms-receiver/files/555085/build.txt)

**Comment by Girjashanker** [comment]
You Have to change this  line from this line to 
SmsReceiver.startReception(({messageBody, originatingAddress}) => {

this line
SmsReceiver:startReception(({messageBody, originatingAddress}) => {

don't use . and use the :

**Comment by vespino** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6991325/20622761/9c71c230-b304-11e6-94c2-8363ce78c5f5.png)

**Comment by Girjashanker** [comment]
var smsInboxPlugin = cordova.require('cordova/plugin/smsinboxplugin');

smsInboxPlugin.isSupported ((function(supported) {
    if(supported) 
      alert("SMS supported !");
    else
      alert("SMS not supported");
  }), function() {
    alert("Error while checking the SMS support");
  });




smsInboxPlugin:startReception (function(msg) {
       alert(msg);
  }, function() {
      alert("Error while receiving messages");
  });

**Comment by Girjashanker** [comment]
use this code

**Comment by vespino** [comment]
Thank, this code does not give any errors. Haven't tested the workings of it yet, but my Android just died on my. Guess it will work, if not I'll get back to you.
